# Global configuration
device.brightness=240
device.cursor_color=0x787878

# Per track settings
track.0.init_note=24
track.0.init_pattern=0b11111111
track.0.range=3
track.0.midi_channel=4

track.1.init_note=16
track.1.init_pattern=0b10100100
track.1.range=3
track.1.midi_channel=3

track.2.init_note=8
track.2.init_pattern=0b00100010
track.2.range=3
track.2.midi_channel=2

track.3.init_note=0
track.3.init_pattern=0b10001000
track.3.range=3
track.3.midi_channel=1

# Note mappings
note.0.color=0xE4D41A
note.1.color=0x9C700E
note.2.color=0xFEFE00
note.3.color=0xFEAE00
note.4.color=0xFE7400
note.5.color=0xFE5A00
note.6.color=0xFE2C00
note.7.color=0xFE1800
note.8.color=0x52FE78
note.9.color=0x5EFE5A
note.10.color=0x00FE00
note.11.color=0x00DC16
note.12.color=0x00FE28
note.13.color=0x0CFE20
note.14.color=0x38FE60
note.15.color=0xFFFF00
note.16.color=0x14F264
note.17.color=0x5EFE5A
note.18.color=0x0000FE
note.19.color=0x0042FE
note.20.color=0x00ACFE
note.21.color=0x00FEFE
note.22.color=0x00FE92
note.23.color=0x14F264
note.24.color=0xFE1A60
note.25.color=0xFE0000
note.26.color=0xFE0006
note.27.color=0xFE0016
note.28.color=0xFE161A
note.29.color=0xFE4036
note.30.color=0xFE5E44
note.31.color=0xFE823E

