#ifndef MUSIN_AUDIO_AUDIO_INPUT_H
#define MUSIN_AUDIO_AUDIO_INPUT_H

#include "musin/audio/block.h"
#include "musin/audio/line_in_source.h"
#include <cstddef>

namespace musin::audio {

/**
 * @brief Captures the codec's I2S output (line input) into a DMA ring buffer.
 *
 * Uses a PIO state machine slaved to the clocks generated by the I2S output
 * state machine, so AudioOutput::init() must have succeeded before init() is
 * called. Stereo frames are downmixed to mono in read_samples().
 *
 * Requires PICO_AUDIO_I2S_DATA_IN_PIN to be defined by the board; on boards
 * without it, init() fails and read_samples() returns 0.
 */
class AudioInput : public BlockReader {
public:
  bool init();
  void deinit();

  /**
   * @brief Reads up to out.size() mono samples from the capture ring buffer.
   * @return The number of samples written (0 when no data is available).
   */
  size_t read_samples(AudioBlock &out) override;
};

} // namespace musin::audio

#endif // MUSIN_AUDIO_AUDIO_INPUT_H
