/*
 * Custom board definition for DATO Submarine
 */

// pico_cmake_set PICO_PLATFORM=rp2350

#ifndef _BOARDS_DATO_SUBMARINE_H
#define _BOARDS_DATO_SUBMARINE_H

// For board detection
#define DATO_SUBMARINE

// --- UART ---
#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART 0
#endif
#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN 0
#endif
#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN 1
#endif

// --- I2C ---
#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C 0
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN 18
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN 19
#endif

// --- WS2812 ---
#ifndef PICO_DEFAULT_WS2812_PIN
#define PICO_DEFAULT_WS2812_PIN 16
#endif

// --- Audio ---
#ifndef PICO_AUDIO_I2S_DATA_PIN
#define PICO_AUDIO_I2S_DATA_PIN 22
#endif
#ifndef PICO_AUDIO_I2S_CLOCK_PIN_BASE
#define PICO_AUDIO_I2S_CLOCK_PIN_BASE 23
#endif
#ifndef DATO_SUBMARINE_CODEC_RESET_PIN
#define DATO_SUBMARINE_CODEC_RESET_PIN 20
#endif

// --- FLASH ---
#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1
#ifndef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 2
#endif
#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)
#endif

// --- GPIO ---
// Analog Multiplexer & ADC
#ifndef DATO_SUBMARINE_MUX_ADDR0_PIN
#define DATO_SUBMARINE_MUX_ADDR0_PIN 6
#endif
#ifndef DATO_SUBMARINE_MUX_ADDR1_PIN
#define DATO_SUBMARINE_MUX_ADDR1_PIN 7
#endif
#ifndef DATO_SUBMARINE_MUX_ADDR2_PIN
#define DATO_SUBMARINE_MUX_ADDR2_PIN 8
#endif
#ifndef DATO_SUBMARINE_MUX_ADDR3_PIN
#define DATO_SUBMARINE_MUX_ADDR3_PIN 9
#endif
#ifndef DATO_SUBMARINE_ADC_PIN
#define DATO_SUBMARINE_ADC_PIN 26
#endif

// Keypad Matrix Columns
#ifndef DATO_SUBMARINE_KEYPAD_COL1_PIN
#define DATO_SUBMARINE_KEYPAD_COL1_PIN 14
#endif
#ifndef DATO_SUBMARINE_KEYPAD_COL2_PIN
#define DATO_SUBMARINE_KEYPAD_COL2_PIN 13
#endif
#ifndef DATO_SUBMARINE_KEYPAD_COL3_PIN
#define DATO_SUBMARINE_KEYPAD_COL3_PIN 12
#endif
#ifndef DATO_SUBMARINE_KEYPAD_COL4_PIN
#define DATO_SUBMARINE_KEYPAD_COL4_PIN 11
#endif
#ifndef DATO_SUBMARINE_KEYPAD_COL5_PIN
#define DATO_SUBMARINE_KEYPAD_COL5_PIN 10
#endif

// LED Driver
#ifndef DATO_SUBMARINE_LED_ENABLE_PIN
#define DATO_SUBMARINE_LED_ENABLE_PIN 17
#endif

// The GPIO Pin used to read VBUS to determine if the device is battery powered.
#ifndef PICO_VBUS_PIN
#define PICO_VBUS_PIN 29
#endif

#endif