name: Test and lint c++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-format
        run: sudo apt install -y clang-format

      - name: clang-format version
        run: clang-format --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        run: bash format.sh check

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Catch2
        run: git submodule update --init musin_test/Catch2

      - name: Checkout etl
        run: git submodule update --init lib/etl

      - name: Test Musin
        working-directory: musin_test
        run: bash ./run_tests.sh


