name: Experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Build examples
        run: bash ./build_experiments.sh
