name: Experiments

on:
  push:
    branches: [ "main" ]


Build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build examples
      run: bash ./build_examples.sh
