name: Experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gcc-arm
        run: sudo apt install -y arm-none-eabi-gcc

      - name: Checkout
        uses: actions/checkout@v4

      - id: cache-pico-build
        name: Cache Pico build deps
        uses: actions/cache@v4
        env:
          cache-name: pico-build
        with:
          path: |
            musin/ports/pico/pico-sdk
            musin/ports/pico/pico-extras
            musin/ports/pico/libraries

          key: ${{ runner.os }}-build-${{ env.cache-name }}-catch2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Build examples
        run: bash ./build_experiments.sh
