name: Experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gcc-arm
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.3.Rel1'

      - name: Checkout
        uses: actions/checkout@v4

      - id: cache-pico-build
        name: Cache Pico build deps
        uses: actions/cache@v4
        env:
          cache-name: pico-build
        with:
          path: |
            musin/ports/pico/pico-sdk
            musin/ports/pico/pico-extras
            musin/ports/pico/libraries
            lib

          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Install picotool
        run: |
          git clone https://github.com/raspberrypi/picotool.git
          cd picotool
          mkdir build
          cd build
          cmake -DPICO_SDK_PATH=musin/ports/pico/pico-sdk ..
          make
          make install

      # - name: Build examples
      #   run: bash ./build_experiments.sh
