name: Main firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Required for GitHub Actions cache to work with root-owned directories in containers
      - name: Allow caching of root-owned directories
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

      - name: Checkout
        uses: actions/checkout@v4

      - id: cache-pico-sdk
        name: Cache pico SDK
        uses: actions/cache@v4
        env:
          cache-name: cache-pico-sdk
        with:
          path: musin/ports/pico/pico-sdk
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - if: ${{ steps.cache-pico-sdk.outputs.cache-hit != 'true' }}
        name: Checkout pico SDK
        run: git submodule update --init --recursive musin/ports/pico/pico-sdk

      - id: cache-extras
        name: Cache pico extras
        uses: actions/cache@v4
        env:
          cache-name: cache-extras
        with:
          path: musin/ports/pico/pico-extras
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - if: ${{ steps.cache-extras.outputs.cache-hit != 'true' }}
        name: Checkout pico extras
        run: git submodule update --init --recursive musin/ports/pico/pico-extras

      - id: cache-pico-vfs
        name: Cache pico pico-vfs
        uses: actions/cache@v4
        env:
          cache-name: cache-pico-vfs
        with:
          path: musin/ports/pico/libraries/pico-vfs
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - if: ${{ steps.cache-pico-vfs.outputs.cache-hit != 'true' }}
        name: Checkout pico pico-vfs
        run: git submodule update --init --recursive musin/ports/pico/libraries/pico-vfs

      - id: cache-etl
        name: Cache ETL
        uses: actions/cache@v4
        env:
          cache-name: cache-etl
        with:
          path: lib/etl
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - if: ${{ steps.cache-etl.outputs.cache-hit != 'true' }}
        name: Checkout etl
        run: git submodule update --init lib/etl

      - name: Install gcc-arm
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '14.2.Rel1'

      - id: cache-picotool
        name: Cache picotool
        uses: actions/cache@v4
        env:
          cache-name: cache-picotool
        with:
          path: |
            /usr/local/bin/picotool
            /usr/local/lib/cmake/picotool
            /usr/local/share/picotool
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - if: ${{ steps.cache-picotool.outputs.cache-hit != 'true' }}
        name: Install picotool
        run: |
          git clone https://github.com/raspberrypi/picotool.git
          cd picotool
          mkdir build
          cd build
          cmake -DPICO_SDK_PATH=../../musin/ports/pico/pico-sdk ..
          make
          sudo make install


      - name: Build firmware
        working-directory: drum
        run: cmake -S . -B build -DPICO_BOARD=dato_submarine && cd build && make -j

      # Cleanup build artifacts and cache on failure to prevent pollution
      - name: Cleanup on failure
        if: failure()
        run: |
          echo "Build failed, cleaning up artifacts and cache..."
          # Remove build directory
          rm -rf drum/build
          # Clear any temporary cmake files
          find . -name "CMakeCache.txt" -delete 2>/dev/null || true
          find . -name "CMakeFiles" -type d -exec rm -rf {} + 2>/dev/null || true
          # Remove any corrupted cache keys by invalidating them
          echo "::warning::Build failed - cached dependencies may need to be refreshed on retry"
